cmake_minimum_required(VERSION 3.16)
project(g2_chapter12)
set(CMAKE_CXX_STANDARD 17)
add_compile_options(-Wall -Wextra -Wpedantic)
find_package(ament_cmake REQUIRED)
find_package(ament_cmake_python REQUIRED)
find_package(ament_index_cpp REQUIRED)
find_package(rclcpp REQUIRED)
find_package(rclcpp_action REQUIRED)
find_package(nav2_msgs REQUIRED)
find_package(nav_msgs REQUIRED)
find_package(control_msgs REQUIRED)
find_package(moveit_ros_planning_interface REQUIRED)
find_package(moveit_core REQUIRED)
find_package(moveit_msgs REQUIRED)
find_package(tf2_ros REQUIRED)
find_package(tf2_geometry_msgs REQUIRED)
find_package(std_msgs REQUIRED)
find_package(geometry_msgs REQUIRED)
find_package(shape_msgs REQUIRED)
find_package(yaml-cpp REQUIRED)
ament_python_install_package(g2_mobile)
add_executable(mission src/mission.cpp)
ament_target_dependencies(mission ament_index_cpp rclcpp rclcpp_action nav2_msgs nav_msgs control_msgs
  moveit_ros_planning_interface moveit_core moveit_msgs tf2_ros tf2_geometry_msgs std_msgs geometry_msgs shape_msgs)
target_link_libraries(mission yaml-cpp)
install(TARGETS mission DESTINATION lib/${PROJECT_NAME})
install(PROGRAMS g2_mobile/controller.py g2_mobile/perception.py DESTINATION lib/${PROJECT_NAME})
install(DIRECTORY launch config urdf srdf rviz maps models DESTINATION share/${PROJECT_NAME})
install(FILES .setup_assistant DESTINATION share/${PROJECT_NAME})
ament_package()
